# Generated by Django 4.2.16 on 2024-11-05 23:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbre',
            fields=[
                ('id_arbre', models.BigAutoField(primary_key=True, serialize=False)),
                ('espece', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'espèce")),
                ('age', models.IntegerField(blank=True, null=True, verbose_name="Age de l'arbre")),
                ('circonferance', models.FloatField(blank=True, null=True, verbose_name='Circonférance (cm)')),
                ('hauteur', models.FloatField(blank=True, null=True, verbose_name='Hauteur (m)')),
                ('geometrie_arbre', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
